### ISSUE TITLE
Angular frontend doesn't run correctly on OpenShift

### ISSUE THREAD

**Issue by edewit** [fabric8-launcher/launcher-creator-backend#126]
Output from angular on OpenShift is not the same as running it locally it just shows an index with files instead of the actual web page:

![screenshot from 2018-12-14 15-10-11](https://user-images.githubusercontent.com/51133/50007858-97275900-ffb2-11e8-8225-8ded028438db.png)

**Comment by quintesse** [comment]
Good catch! Will look into it ASAP

**Comment by quintesse** [comment]
Creating an Angular-only project shows just an index with the project files instead of serving up the index.html.

Going into the terminal of the running Pod I see the following directory structure:

```
/opt/
   app-root/
      etc/
      output/
      src/
```

Where `/opt/app-root/src` seems to contain all the sources (including an empty `dist` folder) and  `/opt/app-root/output` seems to contain the files that you see when you navigate to the URL.

Btw, running the app locally seems to work according to @edewit (didn't try it myself)

**Comment by quintesse** [comment]
There's also an `OUTPUT_DIR=dist` env var set on both the DeploymentConfig and the BuildConfig. But it doesn't seem to actually use it. See https://github.com/nodeshift/centos7-s2i-web-app#configuration for the docs about ENV vars with this builder image

**Comment by quintesse** [comment]
@ia3andy has some experience with this S2I image too, so he can probably help. And otherwise Lance from the Node team.

**Comment by quintesse** [comment]
Btw, the _best_ option would be if we can somehow convince S2I to build in the `src/dist` folder because this would mimic to developer's local situation and running `gap push` would be as efficient as possible (things that are already built wouldn't have to be rebuilt again on the server)
