### ISSUE TITLE
Deploy the landing page as a separate configured service

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-creator-backend#29]
The generated apps should have a welcome screen 

GitHub Repository: https://github.com/fabric8-launcher/application-creator-landingpage
Example: https://fabric8-launcher.github.io/application-creator-landingpage/

**Comment by quintesse** [comment]
There was an idea from the team to just create a single global React app with a Welcome Screen that contains elements/pages for all capabilities. That app would live in its own repo and be directly provisioned into the user's project, The only thing it would need would be a way to tell it which capabilities the project contains so it can show only the relevant ones.

The simplicity of this idea is its great advantage. You'd just need to add a single fixed template fragment to the project for a separate Node/React service and be done with it. No need to generate anything (besides passing some info about the selected capabilities, this could be ENV vars or a mounted .json file or some such).

The worry I personally have is that it might make community involvement harder. Right now it would be easy for people to create their own (local or possibly even private) capabilities, but they would have no easy way to do the same for the welcome page.

**Comment by gastaldi** [comment]
@quintesse if any changes need to be done in the welcome page, the community could just fork the Github repository to make the appropriate changes (and provide a PR back to the official repository if necessary). 

Ideally each entry in the `ApplicationProfile` configuration could be associated to a React component. making easier to extend the frontend by simply creating the new React component,

**Comment by quintesse** [comment]
So one of the way of doing this that we discussed is to add a ConfigMap for the ApplicationProfile information. The Welcome App itself would just be a separate service.

I'll mention some things here that could/should probably be turned into separate issues:

 - Create a generator for the resources needed to create the Welcome App (*)
   - BuildConfig / Service / Route etc
   - ConfigMap holding the necessary configuration
   - Label the Welcome App resources with some special label so you can select all components easily (mainly for getting rid of them)

Btw, projects can still have actual frontends generated for them, they would just not be part of the Welcome App. They would probably be examples of actual UIs written in a way that might interest the user. The Welcome App would most likely still link to them. An example of this might be a frontend for the CRUD capability: the frontend is written in the user's chosen technology, the Welcome Page (written with Node/React) would just link to it.

(*) Not sure yet if this should be a Generator or not, My preference would be to create a separate .yaml file for the Welcome App (eg `service-welcome.yaml`) instead of adding it to the `application.yaml`. This way it would be very easy for the user to remove any trace of the Welcome App from their project. But Generators right now by default only deal with the `application.yaml` resource file.

But perhaps that's okay. Because we probably don't need other Generators adding stuff to or changing anything in the `service-welcome.yaml` so we could create one that just directly writes that file to the `.openshiftio` folder.
